
import "./src/assets/css/animate.min.css"
import "./src/assets/css/bootstrap.min.css"
// import "./src/assets/css/owl.carousel.min.css"
// import "./src/assets/css/owl.theme.default.min.css"
import "./src/assets/css/magnific-popup.css"
import "./src/assets/css/font-awesome.min.css"
import "./src/assets/css/swiper.min.css"
import "./src/assets/css/bootstrap-select.min.css"
import "./src/assets/plugins/potisen-icons/style.css"
// import "./src/assets/css/vegas.min.css"
import "./src/assets/css/style.css"
import "./src/assets/css/responsive.css"
